sudo: required
services:
  - docker

before_install:
  - docker build -t athlant/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true athlant/docker-react npm run test

language: generic